### ISSUE TITLE
Confusing error report from URLError

### ISSUE THREAD

**Issue by duncanmmacleod** [ligovirgo/dqsegdb#10]
I'm getting the following confusing extra error information every time I make a query for a flag that doesn't exist:

```
Warning: Issue accessing url: https://segments.ligo.org/dq/L1/FAKE_CAT5/1?s=1116806416&e=1116892816&include=metadata,active,known
Code: 
404
Message: 
Not Found
May be handled cleanly by calling instance: otherwise will result in an error.
```

What does the last line mean? And why is this not part of the actual error message (which I `try/except` so shouldn't see)?

**Comment by rpfisher** [comment]
This is an intentional error handling sub-case to inform the user that the IFO/FLAG/VERSION requested didn't exist.  In some clients, this should be ignored, but produce a warning.  In other clients, it is a critical failure.
