### ISSUE TITLE
Documentation needed to indicate glue dependency somewhere.

### ISSUE THREAD

**Issue by rpfisher** [ligovirgo/dqsegdb#27]

**Comment by robertbruntz** [comment]
@rpfisher Can you provide more details on this?  Was this addressed by the addition of `lscsoft-glue` to [requirements.txt](https://github.com/ligovirgo/dqsegdb/blob/master/requirements.txt) and [setup.py](https://github.com/ligovirgo/dqsegdb/blob/master/setup.py)?

**Comment by robertbruntz** [comment]
This issue is being closed because it has been moved to the new repo, here: https://git.ligo.org/computing/dqsegdb/client/-/issues/27
