### ISSUE TITLE
Proposed restructuring of dqsegdb package

### ISSUE THREAD

**Issue by duncanmmacleod** [ligovirgo/dqsegdb#33]
I would like to propose a restructuring of the `dqsegdb` package, in order to make the layout more intuitive for users. Rather than the current modules `apicalls`, `urifunctions`, etc, which are very specific to the technical operations behind the API, I think it makes more sense to have modules like `query`, and `insert` that represent user operations.

So, I would propose the following modules

- `dqsegdb.query`- methods to retrieve data from the database
- `dqsegdb.insert` - methods to insert data into the database
- `dqsegdb.connect` - `urllib`/`httplib` extensions for connecting to the rest API
- `dqsegdb.utils` - other things (e.g. certificate discovery/validation)

Given that these don't overlap with the current modules we could easily restructure the modules as above and leave the old ones in place with appropriate `DeprecationWarnings` at the module and function level.

**Comment by duncanmmacleod** [comment]
@rpfisher, any thoughts on this?

**Comment by rpfisher** [comment]
The package layout is designed with application developers in mind.  The functions are organized by how they are useful to an application developer, not a client tool user.  Given that client tool users do not care about the organization of the package, it is better to keep the package organized as it is.  If you notice any functions that are in the wrong category, please do suggest a move of those fuctions.

**Comment by duncanmmacleod** [comment]
I strongly disagree with the statement that client tool users do not carea bout the organisation of the package. I think this is a very narrow view that people will only use the client through the command line.

If the client was better organised, and done from a client user in mind, more people would directly use the client tools, and not rely on third-party libraries on top, e.g. gwpy.

**Comment by rpfisher** [comment]
Maybe you are not agreeing on my definition of application developer vs. client tool user.  Regardless, the design of the package is setup in a tiered structure to make it easier for users to develop or use the python client direclty:  A user wishing to develop new tools or to use these tools directly should be able to work directly with the apicalls, and should not need to rewrite any of the helper functions in the other modules.  If you would like to argue that we split the apicalls into multiple modules or that they are incomplete in functionality or that their uses are unclear, any of those would be accepted suggestions for modification to the organization.

**Comment by duncanmmacleod** [comment]
I disagree with the statement that a client tool user would not want to use python functions. The client is provided as a python package, so they should be able to use it.

My argument is to restructure the package according what the users (be them individuals sitting at a console, or monolithic pipelines running on a cluster) want to do, namely 'query for some segments', or 'insert some segments'. I just think it makes more sense to develop around the goal, not the method, of what the package provides.

Currently, the typical interaction looks like:

```python
>>> from dqsegdb.apicalls import dqsegdbQueryTimes
>>> data = dqsegdbQueryTimes('https', 'segments.ligo.org', 'H1', 'DMT-ANALYSIS_READY', 1, 'active,known', 1126259430, 1126259494)
```

Under such a reorganisation the typical interaction would be something like

```python
>>> from dqsegdb.query import query
>>> data = query('H1:DMT-ANALYSIS_READY:1', 1126259430, 1126259494)
```

(omitted parameters would then be keyword arguments with defaults).
