### ISSUE TITLE
PyOpenSSL version

### ISSUE THREAD

**Issue by spxiwh** [ligovirgo/dqsegdb#44]
We just ran into this issue on the PyCBC automated Travis tests:

https://github.com/cloudera/hue/issues/205

Basically there is a bug in pyOPenSSL 0.13. Can dqsegdb declare that it needs pyOpenSSL >= 0.14, where this is fixed.

Potential problem here is that Caltech is using pyOpenSSL 0.13.1 ... Presumably the OpenSSL libraries there are old enough that the bug isn't present.

**Comment by rpfisher** [comment]
Fixed in #57f0908343484902d189e6615b75f9399b76a8aa .

**Comment by spxiwh** [comment]
Thanks!
