### ISSUE TITLE
M2Crypto error when running PyCBC workflow

### ISSUE THREAD

**Issue by tdent** [ligovirgo/dqsegdb#49]
On atlas, the command 

`/cvmfs/oasis.opensciencegrid.org/ligo/sw/pycbc/x86_64_deb_8/virtualenv/pycbc-v1.10.1/bin/ligolw_segments_from_cats_dqsegdb --separate-categories --segment-url https://segments.ligo.org --veto-file /home/tdent/tests/sarah_snr2p5_inj/output/results/1._analysis_time/1.01_segment_data/H1L1-CBC_VETO_DEFINER_CLEANED_C02_O2_1164556817-23176801.xml --veto-categories 1 --ifo-list H1 --gps-start-time 1187312718 --gps-end-time 1187740818`

gives an error message 

> ligo_data_find requires M2Crypto
>
> On CentOS 5 and other RHEL based platforms
> this package is available from the EPEL
> repository by doing
>
> yum install m2crypto
>
> For Debian Lenny this package is available
> by doing
>
> apt-get install python-m2crypto
>
> Mac OS X users can find this package in
> MacPorts.
>
> No module named M2Crypto

The relevant glue version is glue-release-1.58.2 (ed01d8c).

**Comment by ahnitz** [comment]
@rpfisher Is there a resolution to this yet?

**Comment by rpfisher** [comment]
Fixed in glue here: https://git.ligo.org/lscsoft/glue/tags/glue-release-1.59.2
