### ISSUE TITLE
Error with parse() and eoCB

### ISSUE THREAD

**Issue by rbruntzGH** [ligovirgo/dqsegdb#54]
https://github.com/ligovirgo/dqsegdb/blob/bd3bc8babecc84408377df044800c6724b39bece/dqsegdb/apicalls.py#L692

This commit doesn't work with the current version of GLUE.  It produces the error "(parse() got an unexpected keyword argument 'eoCB')".

**Comment by robertbruntz** [comment]
This issue is being closed because it has been moved to the new repo, here: https://git.ligo.org/computing/dqsegdb/client/-/issues/54
