### ISSUE TITLE
port to ligo.segments

### ISSUE THREAD

**Issue by cannon-zz** [ligovirgo/dqsegdb#59]
The attached patch ports dqsegdb from glue.segments to ligo.segments.  this is required by the upcoming removal of glue.segments from LDG clusters.

[0001-port-to-ligo.segments.patch.gz](https://github.com/ligovirgo/dqsegdb/files/2874121/0001-port-to-ligo.segments.patch.gz)

**Comment by rpfisher** [comment]
@cannon-zz Thanks!  Do you not want to make this into a merge request for some reason?  I can make the merge request up if not.

**Comment by rpfisher** [comment]
@cannon-zz I'm seeing a lot of "patch does not apply" errors when trying to run, this.  If you can quickly rebase, it'll save me a bit of time.  Thanks!

**Comment by cannon-zz** [comment]
I'm not setup to do github, so rebasing is a challenge and pull requests are not possible.  I have constructed a new patch, but please apply it before making other changes to the tree.
[0001-port-to-ligo.segments.patch.gz](https://github.com/ligovirgo/dqsegdb/files/2883865/0001-port-to-ligo.segments.patch.gz)
