### ISSUE TITLE
Problem in accessing segments.ligo.org

### ISSUE THREAD

**Issue by cavaglia** [ligovirgo/dqsegdb#6]
I have a new undergrad student at UMiss (user: jeffrey.atkinson) and he's trying to run this simple python script to retrieve ANALYSIS_READY segments. The script works fine for me, but he gets the error pasted at the bottom. Any help would be appreciated. Thanks. Marco

 ------------------
Script:

      #!/usr/bin/env python

      import sys, optparse
      from gwpy.segments import (DataQualityFlag, DataQualityDict)

      parser = optparse.OptionParser()

      parser.add_option('-s', '--start_time',
          action="store", dest="start_time",
          help="Start time", default=0)

      parser.add_option('-e', '--end_time',
          action="store", dest="end_time",
          help="End time", default=0)

      parser.add_option('-f', '--flag',
          action="store", dest="flag",
          help="Flag", default=0)

      options, args = parser.parse_args()

      print 'Retrieving', options.flag, 'segments from GPS time', options.start_time, 'to GPS time', options.end_time

      filename = options.flag + '_' + options.start_time + '-' + options.end_time + '.txt'

      f = open(filename, "w")
      locked_times = DataQualityFlag.query_dqsegdb(options.flag, options.start_time, options.end_time, url="https://segments.ligo.org/ [segments.ligo.org]").active

      for segments in locked_times:
          f.write(str(segments[0])+"\t"+str(segments[1])+"\n")

      f.close()

 ---------------
Traceback error:

      Retrieving L1:DMT-ANALYSIS_READY segments from GPS time 1127520017 to GPS time 1127590400
      Warning: Issue accessing url: https://segments.ligo.org//dq/L1/DMT-ANALYSIS_READY [segments.ligo.org]
      Code:
      500
      Message:
      Internal Server Error
      May be handled cleanly by calling instance: otherwise will result in an error.
      Traceback (most recent call last):
        File "/home/cavaglia/PCAT_flags/get_flag_times.py", line 29, in <module>
          locked_times = DataQualityFlag.query_dqsegdb(options.flag, options.start_time, options.end_time, url="https://segments.ligo.org/ [segments.ligo.org]").active
        File "/mnt/home1/detchar/opt/gwpysoft/lib64/python2.6/site-packages/gwpy/utils/deps.py", line 82, in wrapper
          return func(*args, **kwargs)
        File "/mnt/home1/detchar/opt/gwpysoft/lib64/python2.6/site-packages/gwpy/segments/flag.py", line 496, in query_dqsegdb
          start, end)
        File "/usr/lib/python2.6/site-packages/dqsegdb/apicalls.py", line 573, in dqsegdbCascadedQuery

      result_flag,affected_results=clientutils.calculate_versionless_result(jsonResults,startTime,endTime,ifo_input=ifo)
      UnboundLocalError: local variable 'jsonResults' referenced before assignment

**Comment by rpfisher** [comment]
Resolved over email.
