### ISSUE TITLE
error raised in ligolw_segments_from_cats_dqsegdb

### ISSUE THREAD

**Issue by tcarver1234** [ligovirgo/dqsegdb#63]
File "/home/spxtc4/.conda/envs/pycbc-pygrb-o3/bin/ligolw_segments_from_cats_dqsegdb", line 432, in <module>
    vetoed_segments = reduce(operator.or_, vetoed_segments).coalesce()
NameError: name 'reduce' is not defined

**Comment by pannarale** [comment]
`ligolw_segments_from_cats_dqsegdb` is missing an `from six.moves import reduce`.  @rpfisher, could you fix this?  It gets used by PyGRB.  Thanks!

**Comment by glth** [comment]
`reduce` ceased being a built-in library as of Python 3, when it was moved into `functools`:
`from functools import reduce`

**Comment by pannarale** [comment]
So `dqsegdb/clientutils.py` may have to be fixed accordingly because it has `from six.moves import reduce`

**Comment by rpfisher** [comment]
@tcarver1234 @pannarale Done in c7fc62a940d6fb5c5f461946df61af6a530a55b5 .  Do you need me to build a new package for this or a tag or can you grab it from master?

**Comment by robertbruntz** [comment]
Modified the code from `from six.moves import reduce` (retained as a comment) to `from functools import reduce`, in anticipation of eventually getting rid of `future` and `six`.

**Comment by robertbruntz** [comment]
This was fixed in one of the (many) commits included in https://github.com/ligovirgo/dqsegdb/pull/87, which was merged on 2022.01.26.
