### ISSUE TITLE
exception raised in ligolw_dq_query_dqsegdb with conflict between -o and -a options

### ISSUE THREAD

**Issue by reedessick** [ligovirgo/dqsegdb#7]
I found a bug:

```bash
$ ligolw_dq_query_dqsegdb -t https://segments.ligo.org -s -30 -e 30 -o /home/gracedb.processor/users/ressick/working/seglogic//allActive-1136862098-61.json 1136862128 -a
```

prints a lot of stuff but then exits with an exception

```
Traceback (most recent call last):
  File "/usr/bin/ligolw_dq_query_dqsegdb", line 377, in <module>
    out_dict['Known but Inactive Results']=known_results
NameError: name 'known_results' is not defined
```
and I think this exception is raised before the output file is written (the output file does not exist).

Ryan Fisher identified this as a conflict between the -a and -o options and the client runs without error when only one is provided.

**Comment by rpfisher** [comment]
Fixed in 0ccd85aee79476cb117ea02dd583dd7b34f8ab41
