### ISSUE TITLE
Separate client and server source into separate repositories

### ISSUE THREAD

**Issue by duncanmmacleod** [ligovirgo/dqsegdb#82]
It makes sense to me to separate out the client and server components of this repository into separate repositories. I have tested extracting the `server/` directory using `git filter-repo --subdirectory-filter server` and the result is here if someone cares to investigate it:

<https://git.ligo.org/duncanmmacleod/dqsegdb-server/>

**Comment by duncanmmacleod** [comment]
One a server repo is created and supported, the server code can be excised from the client repo using the inverse operation with `git filter-repo`:

```shell
git filter-repo --subdirectory-filter server --invert-paths
```

**Comment by robertbruntz** [comment]
This issue was moved to the new repo as https://git.ligo.org/computing/dqsegdb/client/-/issues/82 and subsequently closed as completed.
