### ISSUE TITLE
Remove bdist directory from repository (and history)

### ISSUE THREAD

**Issue by duncanmmacleod** [ligovirgo/dqsegdb#95]
The `/bdist/` directory contains compiled binaries for two very old distributions. IMO this directory should never be under version control, so can this be excised from the repository and the history? This would make the repository much smaller to clone.

**Comment by robertbruntz** [comment]
This issue was moved to the new repo as https://git.ligo.org/computing/dqsegdb/client/-/issues/95 and subsequently completed and closed.
